name: Release Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LATEST_PYTHON_VER: "3.10"
  LATEST_QBT_VER: "v4.4.4"
  SUBMIT_COVERAGE_VERSIONS: "2.7, 3.10"
  QBITTORRENTAPI_HOST: "localhost:8080"
  QBITTORRENTAPI_PASSWORD: "adminadmin"
  QBITTORRENTAPI_USERNAME: "admin"
  DOCKER_IMAGE_NAME: "ghcr.io/rmartin16/qbittorrent-nox"
  LATEST_DOCKER_IMAGE: "ghcr.io/rmartin16/qbittorrent-nox:debug"
  DOCKER_ARGS: "--name qbt --detach --publish 8080:8080 --volume ${{ github.workspace }}/tests/resources:/tmp/resources"

jobs:
  verify:
    name: Get Ready
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      qbittorrent-latest-version: ${{ steps.set-qbittorrent-latest-version.outputs.qbittorrent-latest-version }}
      python-latest-version: ${{ steps.set-python-latest-version.outputs.python-latest-version }}
    steps:
      - name: Declare Latest qBittorrent Version
        id: set-qbittorrent-latest-version
        run: echo "::set-output name=qbittorrent-latest-version::${LATEST_QBT_VER}"

      - name: Declare Latest Python Version
        id: set-python-latest-version
        run: echo "::set-output name=python-latest-version::${LATEST_PYTHON_VER}"

      - name: Branch
        run: echo Branch ${{ github.ref }} ${{ github.head_ref }}

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.LATEST_PYTHON_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.LATEST_PYTHON_VER }}
          cache: 'pip'
          check-latest: true

      - name: Lint with Pre-commit
        uses: pre-commit/action@v3.0.0

  Tests:
    name: "Release Test ${{ matrix.python-version }} - ${{ matrix.QBT_VER }}"
    needs: [verify]
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          # test all python versions against latest qBittorrent
          - python-version: "3.11-dev"
            QBT_VER: ${{ needs.verify.outputs.qbittorrent-latest-version }}
          - python-version: "3.10"
            QBT_VER: ${{ needs.verify.outputs.qbittorrent-latest-version }}
          - python-version: "3.9"
            QBT_VER: ${{ needs.verify.outputs.qbittorrent-latest-version }}
          - python-version: "3.8"
            QBT_VER: ${{ needs.verify.outputs.qbittorrent-latest-version }}
          - python-version: "pypy3.8"
            QBT_VER: ${{ needs.verify.outputs.qbittorrent-latest-version }}
          - python-version: "3.7"
            QBT_VER: ${{ needs.verify.outputs.qbittorrent-latest-version }}
          - python-version: "pypy3.7"
            QBT_VER: ${{ needs.verify.outputs.qbittorrent-latest-version }}
          - python-version: "3.6"
            QBT_VER: ${{ needs.verify.outputs.qbittorrent-latest-version }}
          - python-version: "3.5"
            QBT_VER: ${{ needs.verify.outputs.qbittorrent-latest-version }}
          - python-version: "2.7"
            QBT_VER: ${{ needs.verify.outputs.qbittorrent-latest-version }}
          - python-version: "pypy2.7"
            QBT_VER: ${{ needs.verify.outputs.qbittorrent-latest-version }}
          # test all qBittorrent versions against latest python
          - QBT_VER: "v4.4.0"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.3.9"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.3.8"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.3.7"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.3.6"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.3.5"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.3.4.1"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.3.3"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.3.2"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.3.1"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.3.0.1"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.2.5"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.2.0"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.1.6"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4.1.0"
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "master"
            IS_QBT_DEV: True
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4_4_x"
            IS_QBT_DEV: True
            python-version: ${{ needs.verify.outputs.python-latest-version }}
          - QBT_VER: "v4_3_x"
            IS_QBT_DEV: True
            python-version: ${{ needs.verify.outputs.python-latest-version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          check-latest: true

      - name: Start qBittorrent ${{ matrix.QBT_VER }}
        run: |
          IMAGE_EXTRA="-debug"
          if [[ ${{ matrix.QBT_VER }} = v4.3.1 || ${{ matrix.QBT_VER }} = v4.3.0.1 ]]; then IMAGE_EXTRA=""; fi
          docker run ${DOCKER_ARGS} ${DOCKER_IMAGE_NAME}:${{ matrix.QBT_VER }}${IMAGE_EXTRA}

      - name: Test with pytest
        run: |
          pip install .[test]
          IS_QBT_DEV=${{ matrix.IS_QBT_DEV }}
          QBT_VER=${{ matrix.QBT_VER }}
          pytest

      - name: qBittorrent Log
        run: docker logs qbt

      - name: Upload Coverage to Codecov
        if: contains(env.SUBMIT_COVERAGE_VERSIONS, matrix.python-version)
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  package:
    #######
    # Verify build and packaging is successful
    #######
    name: Build & Verify Package
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.LATEST_PYTHON_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.LATEST_PYTHON_VER }}
          cache: 'pip'

      - name: Install Build Tools
        run: python -m pip install -U pip setuptools wheel twine build

      - name: Build Package
        run: python -m build

      - name: List Result
        run: ls -l dist

      - name: Check long_description
        run: python -m twine check dist/*

  install-dev:
    #######
    # Verify package can be installed on all platforms
    #######
    name: Verify Dev Install
    needs: [verify]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.LATEST_PYTHON_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.LATEST_PYTHON_VER }}
          cache: 'pip'

      - name: Install in Dev Mode
        run: |
          python -m pip install -U pip wheel setuptools
          python -m pip install -e .[test,dev]

      - name: Import Package
        run: python -c "from qbittorrentapi import Client; assert Client().host == 'localhost:8080'"

  docs-build:
    #######
    # Verify documentation build succeeds
    #######
    name: Verify Doc Build
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.LATEST_PYTHON_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.LATEST_PYTHON_VER }}
          cache: 'pip'

      - name: Install Doc Build Requirements
        run: python -m pip install -r requirements-dev.txt

      - name: Build Docs
        run: |
          cd docs
          sphinx-build -v -W --keep-going -E -a -b linkcheck "source" "build"
          sphinx-build -v -W --keep-going -E -a -b html "source" "build"
          make html
