name: Latest Dev Tests

on:
  schedule:
    - cron: "16 4 * * *"
  workflow_dispatch:

env:
  LATEST_PYTHON_VER: "3.10"
  QBITTORRENTAPI_HOST: "localhost:8080"
  QBITTORRENTAPI_PASSWORD: "adminadmin"
  QBITTORRENTAPI_USERNAME: "admin"
  DOCKER_IMAGE_NAME: "ghcr.io/rmartin16/qbittorrent-nox"
  DOCKER_ARGS: "--name qbt --detach --publish 8080:8080 --volume ${{ github.workspace }}/tests/resources:/tmp/resources"

jobs:
  tests-dev-qbt:
    #######
    # Run tests against dev versions of qBittorrent and latest Python releases
    #######
    name: "Dev Branch Test 3.10 - ${{ matrix.QBT_VER }}"
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      IS_QBT_DEV: true
    strategy:
      matrix:
        QBT_VER: ["master", "v4_4_x", "v4_3_x"]
    steps:
      - name: Branch
        run: echo Branch ${{ github.ref }} ${{ github.head_ref }}

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.LATEST_PYTHON_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.LATEST_PYTHON_VER }}
          cache: 'pip'

      - name: Start qBittorrent ${{ matrix.QBT_VER }}
        run: docker run ${DOCKER_ARGS} ${DOCKER_IMAGE_NAME}:${{ matrix.QBT_VER }}-debug

      - name: Test with pytest
        run: |
          pip install .[test]
          export QBT_VER=${{ matrix.QBT_VER }}
          pytest

      - name: Docker logs
        run: docker logs qbt

      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} failed
          body: |
            ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} failed.
            https://github.com/rmartin16/qbittorrent-api/actions/runs/${{ github.run_id }}
          to: rmartin16+github-action@gmail.com   # comma-separated string
          from: rmartin16+github-action@gmail.com
